version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from=app -t heroku-cli .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar heroku-cli
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Show docker image size
          command: |
            docker images
            ls -l /caches/app.tar
      - run:
          name: Run tests
          command: |
            docker run -it --rm heroku-cli bash -c "heroku --version"
            docker run -it --rm heroku-cli bash -c "git --version"

  update_version:
    working_directory: /app
    docker:
      - image: node
    steps:
      - checkout

      - run:
          name: Install package
          command: |
            apt-get update
            apt-get install jq git -y

      - run:
          name: Setup git
          command: |
            git config push.default current
            git config user.name "CircleCI"
            git config user.email ${EMAIL}

      - run:
          name: Check latest heroku-cli
          command: |
            npm info heroku-cli versions --json | jq --raw-output .[-1:][0] > VERSION

      - run:
          name: Update VERSION
          command: |
            git add VERSION
            set +o pipefail
            git commit -m "Bump version from CircleCI" | true
            set -o pipefail
            git push origin

workflows:
  version: 2

  build:
    jobs:
      - build

  weekly_update:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only: master
    jobs:
      - update_version
